# Generated by Django 5.1.6 on 2025-03-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
