# Generated by Django 5.1.6 on 2025-03-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expectedspeech',
            options={'ordering': ['order', 'word'], 'verbose_name_plural': 'Expected Speeches'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.RenameField(
            model_name='expectedspeech',
            old_name='text',
            new_name='word',
        ),
        migrations.AddField(
            model_name='speechrecord',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speech_processing.language'),
        ),
        migrations.AlterField(
            model_name='category',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='speech_processing.language'),
        ),
        migrations.AlterField(
            model_name='expectedspeech',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expected_speeches', to='speech_processing.language'),
        ),
        migrations.AlterField(
            model_name='speechrecord',
            name='expected_speech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speech_records', to='speech_processing.expectedspeech'),
        ),
        migrations.AlterUniqueTogether(
            name='expectedspeech',
            unique_together={('word', 'language')},
        ),
    ]
