# Generated by Django 5.1.6 on 2025-03-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech_processing', '0002_alter_expectedspeech_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expectedspeech',
            options={'ordering': ['order', 'text'], 'verbose_name_plural': 'Expected Speeches'},
        ),
        migrations.RenameField(
            model_name='expectedspeech',
            old_name='word',
            new_name='text',
        ),
        migrations.AlterUniqueTogether(
            name='expectedspeech',
            unique_together={('text', 'language')},
        ),
    ]
