# Generated by Django 5.1.6 on 2025-03-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_processing', '0003_alter_expectedspeech_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedspeech',
            name='difficulty_level',
            field=models.CharField(default='medium', max_length=50),
        ),
    ]
