# Generated by Django 5.1.6 on 2025-03-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_processing', '0004_expectedspeech_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedspeech',
            name='etymology',
            field=models.TextField(blank=True, help_text='Word origin and historical background', null=True),
        ),
        migrations.AddField(
            model_name='expectedspeech',
            name='example_sentence',
            field=models.TextField(blank=True, help_text='Example sentence showing word usage', null=True),
        ),
        migrations.AddField(
            model_name='expectedspeech',
            name='meaning',
            field=models.TextField(blank=True, help_text='Detailed definition or meaning of the word', null=True),
        ),
        migrations.AddField(
            model_name='expectedspeech',
            name='pronunciation_phonetic',
            field=models.CharField(blank=True, help_text='Phonetic pronunciation guide', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expectedspeech',
            name='synonyms',
            field=models.CharField(blank=True, help_text='Comma-separated list of synonyms', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expectedspeech',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
