# Generated by Django 5.1.6 on 2025-03-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_processing', '0005_expectedspeech_etymology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectedspeech',
            name='etymology',
        ),
        migrations.RemoveField(
            model_name='expectedspeech',
            name='example_sentence',
        ),
        migrations.RemoveField(
            model_name='expectedspeech',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='expectedspeech',
            name='pronunciation_phonetic',
        ),
        migrations.RemoveField(
            model_name='expectedspeech',
            name='synonyms',
        ),
        migrations.AlterField(
            model_name='expectedspeech',
            name='difficulty_level',
            field=models.CharField(default='medium', max_length=50),
        ),
    ]
