# Generated by Django 5.1.6 on 2025-04-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_processing', '0006_remove_expectedspeech_etymology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedspeech',
            name='translation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
